# Generated by Django 2.2.19 on 2021-02-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='beurax',
            field=models.URLField(blank=True, null=True),
        ),
    ]
